version: "3.3"

services:
  apt_db:
    platform: linux/x86_64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "aptdb"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - 3306:3306

  apt_redis:
    image: redis:latest
    ports:
      - 6379:6379

  elasticsearch:
    image: elasticsearch:7.17.0
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200

  kibana:
    image: kibana:7.17.0
    environment:
      ELASTICSERCH_UTL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
